spring:
  application:
    name: api-gateway
server:
  port: 8080

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

zuul:
  prefix: /api
  routes:
    submiting-email-service:
      path: /email/**
      serviceId: SUBMITING-EMAIL-SERVICE
      stripPrefix: false

    main-view-service:
      path: /invitation/**
      serviceId: MAIN-VIEW-SERVICE
      stripPrefix: false
